// player-client/src/views/Final.jsx
import socket from "../socket"
import './Final.css'
export default function Final({ state, playerId, socket }) {
  if (!state?.phase === "VeDich") return null;
  console.log(state.buzzWindow);
  
  const canBuzz =
    state.buzzWindow &&
    state.activePlayer !== socket.id;
  const showContent = state.showContent;
  return (
    <div className="final-container">
      <h1>VỀ ĐÍCH</h1>
      {showContent && (
      <div className="final-question">
        {state.question}
      </div>
      )}
      <div className="final-players">
        {state.players.map((p) => (
          <div className="final-player" key={p.id}>
            <span>{p.name}</span>
            <span>{p.score}</span>
          </div>
        ))}
      </div>

      {canBuzz && (
        <button
          className="final-buzz-btn"
          onClick={() => socket.emit("player:finalBuzz")}
        >
          BẤM CHUÔNG
        </button>
      )}
    </div>
  );
}

// public-screen/src/views/Final.vue
<template>
<div>

  <div v-if="!state.final.packageValue">
    <button>40</button>
    <button>60</button>
    <button>80</button>
  </div>

  <div v-else>

    <h2>
      {{
        state.final.questions[
          state.final.currentIndex
        ]?.text
      }}
    </h2>

    <h3>
      {{
        state.players.find(
          p=>p.id===state.final.activePlayer
        )?.name
      }}
    </h3>

    <div>
      {{
        state.players.map(p=>(
          p.name+" "+p.score
        ))
      }}
    </div>

  </div>

</div>
</template>

<script setup>
import { state } from "../socket"
</script>
