// player-client/src/views/Kickoff.jsx

import React from "react"
import "./Kickoff.css"

export default function Kickoff({ state }) {

  if (!state) return null

  return (
    <div className="kickoff-player">
      <h2>PHẦN KHỞI ĐỘNG</h2>

      {!state.isActive && <h3>Chờ tới lượt...</h3>}

      {state.isActive && (
        <>
          <h3>Thời gian: {state.timer}</h3>

          {state.currentQuestion && (
            <p>
              Câu {state.currentQuestion.number}:{" "}
              {state.currentQuestion.question}
            </p>
          )}
        </>
      )}
    </div>
  )
}

// public-screen/src/views/Kickoff.vue
<template>
  <div class="public">
    <h1>PHẦN KHỞI ĐỘNG</h1>

    <div v-if="activePlayer">
      <h2>{{ activePlayer }}</h2>
      <h3>Thời gian: {{ timeLeft }}</h3>
      <div class="question">{{ question }}</div>
    </div>
  </div>
</template>

<script setup>
import { inject, computed } from "vue"

const state = inject("state")

const activePlayer = computed(() => state.kickoff.activePlayer)

const timeLeft = computed(() =>
  activePlayer.value
    ? state.players[activePlayer.value].kickoff.timeLeft
    : 0
)

const question = computed(() => {
  if (!activePlayer.value) return ""
  const index =
    state.players[activePlayer.value].kickoff.currentQuestionIndex
  return state.kickoff.questions[index]
})
</script>
